# This file was generated by GoReleaser. DO NOT EDIT.
cask "chrome-protocol-proxy" do
  version "0.7.2"

  on_macos do
    on_arm do
      sha256 "05bb85b38dbd9283851f6f27a96c83f5ca82efc8f5066435fbf76e230cc6311c"
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v#{version}/chrome-protocol-proxy_#{version}_darwin_arm64.tar.gz"
      rename "chrome-protocol-proxy_0.7.2_darwin_arm64/chrome-protocol-proxy", "chrome-protocol-proxy"
    end
    on_intel do
      sha256 "5413627b5602f19aacc8c446f5c9eb5d6b201aa31e5714ff490ddb2e117b3ee8"
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v#{version}/chrome-protocol-proxy_#{version}_darwin_amd64.tar.gz"
      rename "chrome-protocol-proxy_0.7.2_darwin_amd64/chrome-protocol-proxy", "chrome-protocol-proxy"
    end
  end
  on_linux do
    on_arm do
      sha256 "f3b1ee421ba3867e7fa74ba63f6a9db80302fcb636868d3a5dfb92931750a45a"
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v#{version}/chrome-protocol-proxy_#{version}_linux_arm64.tar.gz"
      rename "chrome-protocol-proxy_0.7.2_linux_arm64/chrome-protocol-proxy", "chrome-protocol-proxy"
    end
    on_intel do
      sha256 "2d205235db948f01d52eb5058c232b0a41d9bf4a3f624a9889bd69d94b3b0747"
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v#{version}/chrome-protocol-proxy_#{version}_linux_amd64.tar.gz"
      rename "chrome-protocol-proxy_0.7.2_linux_amd64/chrome-protocol-proxy", "chrome-protocol-proxy"
    end
  end

  name "chrome-protocol-proxy"
  desc "chrome-protocol-proxy is small reverse websocket proxy designed for chrome debugging protocol. It's purpose is to capture messages written to and received from Chrome Debugging Protocol, coalesce requests with responses, unpack messages from Target domain and provide easy to read, colored output."
  homepage "https://github.com/wendigo/chrome-protocol-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chrome-protocol-proxy"

  preflight do
    if (HOMEBREW_PREFIX/"Cellar/chrome-protocol-proxy").exist?
      odie "An old chrome-protocol-proxy formula keg is installed and would shadow this cask's binary. Remove it first with: brew uninstall --formula chrome-protocol-proxy"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chrome-protocol-proxy"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Usage: chrome-protocol-proxy -i -m -r localhost:9222
  EOS
end
