# This file was generated by GoReleaser. DO NOT EDIT.
cask "chrome-protocol-proxy" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "b9dd71e15eb4a1e24a4366aff99d143ca08b2390bd645fb273238a1a69bde90f"
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v#{version}/chrome-protocol-proxy_#{version}_darwin_arm64.tar.gz"
      rename "chrome-protocol-proxy_0.7.1_darwin_arm64/chrome-protocol-proxy", "chrome-protocol-proxy"
    end
    on_intel do
      sha256 "ab23902eff8b4f8b5f3c15b9a85a135c39f590d3d5ad9e611a36d08ac17d5e84"
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v#{version}/chrome-protocol-proxy_#{version}_darwin_amd64.tar.gz"
      rename "chrome-protocol-proxy_0.7.1_darwin_amd64/chrome-protocol-proxy", "chrome-protocol-proxy"
    end
  end
  on_linux do
    on_arm do
      sha256 "b5bc209ab7ce767a9f7b49ac685cd86771ddbcc7161ef8e7e7fd4776de347449"
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v#{version}/chrome-protocol-proxy_#{version}_linux_arm64.tar.gz"
      rename "chrome-protocol-proxy_0.7.1_linux_arm64/chrome-protocol-proxy", "chrome-protocol-proxy"
    end
    on_intel do
      sha256 "5d7f1fc527fdf243552f2625f712beb769eae68c3199732cc48009d7dd0e0b72"
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v#{version}/chrome-protocol-proxy_#{version}_linux_amd64.tar.gz"
      rename "chrome-protocol-proxy_0.7.1_linux_amd64/chrome-protocol-proxy", "chrome-protocol-proxy"
    end
  end

  name "chrome-protocol-proxy"
  desc "chrome-protocol-proxy is small reverse websocket proxy designed for chrome debugging protocol. It's purpose is to capture messages written to and received from Chrome Debugging Protocol, coalesce requests with responses, unpack messages from Target domain and provide easy to read, colored output."
  homepage "https://github.com/wendigo/chrome-protocol-proxy"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "chrome-protocol-proxy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/chrome-protocol-proxy"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Usage: chrome-protocol-proxy -i -m -r localhost:9222
  EOS
end
