# This file was generated by GoReleaser. DO NOT EDIT.
class ChromeProtocolProxy < Formula
  desc "chrome-protocol-proxy is small reverse websocket proxy designed for chrome debugging protocol. It's purpose is to capture messages written to and received from Chrome Debugging Protocol, coalesce requests with responses, unpack messages from Target domain and provide easy to read, colored output."
  homepage "https://github.com/wendigo/chrome-protocol-proxy"
  version "0.5.2"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v0.5.2/chrome-protocol-proxy_0.5.2_macos_x86_64.tar.gz"
    sha256 "0f11e3a1de4a148e24341b4beb9fce7d87fa4b2270f1e647672458c675ff575a"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v0.5.2/chrome-protocol-proxy_0.5.2_linux_x86_64.tar.gz"
      sha256 "7d5c6470151d591ebbb6feb77335a52c2b5f77f835d50a35d35f2f858c3bbbcf"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v0.5.2/chrome-protocol-proxy_0.5.2_linux_arm64.tar.gz"
        sha256 "efc41a7ab8f65434936dd441e228fbc96f772e3992a8f43e8596bb61ffa2fe9a"
      else
        url "https://github.com/wendigo/chrome-protocol-proxy/releases/download/v0.5.2/chrome-protocol-proxy_0.5.2_linux_armv6.tar.gz"
        sha256 "a61d3fc75c823e22d151bb47b08d1070c9f01efd18e319237b9d68c956236e95"
      end
    end
  end

  def install
    bin.install "chrome-protocol-proxy"
  end

  def caveats; <<~EOS
    Usage: chrome-protocol-proxy -i -m -r localhost:9222
  EOS
  end
end
